const insults = {
  "descriptor_after": [
    ", a totally overrated clown who speaks without knowing facts,",
    ", a liberal clown,",
    ", an irrelevant clown,",
    ", a highly overrated political pundit,",
    ", whose unwatchable show is dying in the ratings,",
    ", the habitual vacationer,",
    " (is that really a last name?)",
    ", a total lightweight,",
    ", a dishonest slob of a reporter,",
    ", a no-good rotten traitor,",
    ", who wears glasses to make himself look smarter,",


    ", a total lightweight who opposes me and some of our great Republican ideas and policies,",
    ", a third rate lawyer who is good at making false accusations,",
    ", someone who has done very little,",
    ", a mental basketcase,",
    ", who always seems to be crying (worse than Boehner),",
    ", making up story after story,",
    ", an embarrassment to our Country,",
    ", who always ends up badly and out of whack,",
    ", a third rate conman,",
    ", a major sleaze and buffoon,",
    ", someone who would come to my office 'begging' for campaign contributions not so long ago (and would do anything for them),",
    ", a Crooked H flunkie who I don’t speak to and have nothing to do with,",
    ", who has had a failed career,",
    ", who nobody ever heard of,",
    ", who is obviously a madman,",
    ", a total stiff,",
    " (who, like many others, never had a clue)",
    ", who has made serious bad calls,",
    ", a drunk/drugged up loser,",
    ", one of the dumber people on television,",
    ", a dopey political pundit,",
    ", one of the dumber bloggers,",
    ", a total con job,",
    ", a person who is looking to raise Taxes substantially,",
    ", a hater & racist,",
    ", perhaps in a near drunken state,",
    ", an extraordinarily low IQ person,",
    " (check out sex tape and past)"


  ],

  "descriptor_before": [
    "Ratings starved ",
    "Sleepy eyes ",
    "The money losing ",
    "Liberal clown ",
    "Unimportant ",
    "Stupid ",
    "Goofball atheist ",
    "Irrelevant clown ",
    "Highly overrated political pundit ",
    "Dopey clown ",
    "Uncomfortable looking ",
    "Total hypocrite ",
    "Frumpy and very dumb ",
    "Lightweight ",
    "An 'extremely credible' source has called my office and told me that ",
    "This idiot ",
    "Little ",


    "Crime loving ",
    "Crazy ",
    "Sloppy ",
    "No talent ",
    "Low-life ",
    "Sleepy ",
    "Totally dishonest ",
    "Very insecure ",
    "Crooked ",
    "Lyin' ",
    "Wacky Nut Job ",
    "Slippery ",
    "Big Trump Hater ",
    "Crazed and incompetent ",
    "Shady ",
    "Sneaky ",
    "Publicity seeking ",
    "Really dumb ",
    "The virtually incompetent ",
    "The very unpopular ",
    "The very weak and untalented ",
    "The underachieving ",
    "Disgusting ",
    "Ungrateful TRAITOR ",
    "The very foul mouthed ",
    "Angry and obnoxious, ",
    "Disgraced and discredited ",
    "The grandstanding ",
    "Truly weird ",
    "Pelosi Liberal Puppet ",
    "Kooky ",
    "Establishment flunky ",
    "Wacko ",
    "Cryin ",
    "Ousted & discredited ",
    "Weirdo ",
    "Wacky & totally unhinged ",
    "The incompetent & corrupt ",
    "Goofy ",
    "The highly neurotic ",
    "Perv sleazebag ",
    "Deadpan "



  ],

  "subject_in_middle": [
    [ "I've totally been warning about ", " since as early as the 80's. " ],
    [ "I refuse to call ", " a bimbo, because that would not be politically correct. " ],
    [ "All ", " does is go on television is talk, talk, talk, but incapable of doing anything. " ],
    [ "I was never a fan of ", ". " ],
    [ "Question will be, is ", " a Flake? I hope not. " ],
    [ "Why would anybody listen to ", "? " ]
    

  ],

  "predicate": [
    " must have been drunk.",
    " did an absolutely horrible job of securing the border.",
    " is always hitting me politically.",
    " has failed miserably.",
    " owes apology!",
    " should be forced to take an IQ test.",
    " is a fool.",
    " wrote a letter begging me for foregiveness.",
    " has zero cred.",
    " will be fired like a dog.",
    " did really poorly on television this morning.",
    " calls me to ask for favors and then mockingly smiles when told of my high poll numbers.",
    " came to my office looking for $$.",
    " is a total joke, a dummy who is lost!",
    " is a sad joke.",
    " has the mind of a very dumb and backward child.",
    " is an average talent who is out of touch with reality.",
    " is a fraud.",
    " was not born with much of a brain.",
    " is not going to make the country great again.",
    " is a political moron.",
    " is truly dumb as a rock.",
    " fabricated nonsense about me.",
    " calls me a jackass.",


    " was a major security risk.",
    " will destroy the State.",
    " is totally unqualified.",
    " is weak on Vets, the Military and the 2nd Amendment.",
    " is a loser who sadly plays right into our opponents hands!",
    " has embarrassed all by making very dumb political statements about me.",
    " is just a poor man’s version of Don King, but without the hair.",
    " has been dumped like a dog by almost everyone.",
    " did a terrible job against me.",
    " is a failing, crying, lost soul!",
    " has zero credibility.",
    " has knowingly committed fraud.",
    " is weak, both mentally and physically.",
    " cried like a baby and begged for forgiveness.",
    " came to my office begging for money like a dog.",
    " chokes on the truth.",
    " has gone totally off the rails.",
    " will go down as easily the WORST in history.",
    " is a total waste of time.",
    " is a clown with no awareness of the world around.",
    " doesn’t have a clue.",
    " is a 'hell hole' and a mess.",
    " had a mental breakdown while talking about me.",
    " is desperate.",
    " is at the bottom of the barrel.",
    " questioned me in such a nasty fashion.",
    " is totally in the Hillary circle of bias.",
    " has ZERO leadership ability.",
    " committed perjury on a scale not seen before.",
    " has been largely forgotten.",
    " is mathematically dead and totally desperate.",
    " has accomplished absolutely nothing.",
    " lies like a dog-over and over again!",
    " holds the Bible high and then lies and misrepresents the facts!",
    " is the worst liar, crazy or very dishonest. Perhaps all 3?",
    " doesn't have the aptitude or 'smarts' & is a poor public speaker & nervous mess.",
    " just doesn't have IT!",
    " just doesn't know about winning!",
    " is a disgrace.",
    " did such a horrible job.",
    " doesn't have a clue.",
    " is a Flake!",
    " falsely stated that I said there is moral equivalency between the KKK, neo-Nazis & white supremacists.",
    " isn't smart enough to know what is going on at the border.",
    " never called President Donald J. Trump to apologize for the HORRIBLE statements made and said about me on ABC.",
    " begged my people for a job.",
    " is incoherent with anger.",
    " wants to raise your taxes through the roof.",
    " is, and always has been, owned by the banks.",
    " is just wasting time & money!",
    " is so average in so many ways!",
    " was not very good or professional!",
    " is fighting over table scraps.",
    " is about to be fired(?) for incompetence, and much worse.",
    " is truly one of the dumbest of the talking heads.",
    " is a low class slob who came to my office looking for consulting work and I had zero interest.",
    " become totally unglued and weird.",
    " is a total Clinton flunky!",
    " treats me very badly.",
    " is a crude dope!",
    " is not a natural deal maker. Only makes bad deals!",
    " has a horrible attitude.",
    " is weak & ineffective.",
    " is a really stupid talking head.",
    " wants to raise your taxes, open your borders, and take away your 2nd Amendment.",
    " wants to raise your Taxes (by a lot).",
    " wants to protect criminals, allow illegal immigration and raise taxes!",
    " is dodging a Subpoena & is refusing to show up and testify.",
    " has already proven to be a liar.",
    " couldn't be elected dog catcher.",
    " didn't get the right gene.",
    " reminds me of a spoiled brat without a properly functioning brain.",
    " has behaved so irrationally.",
    " is getting nothing done.",
    " will Make America Weak Again!",
    " is going absolutely crazy.",
    " doesn't understand what the word demagoguery means.",
    " should have gone to prison for what you did.",
    " led through lies and deception.",
    " is nasty.",
    " opens up our country to potential terrorists and others that do not have our best interests at heart.",
    " choked like a dog.",
    " is a total joke, and everyone knows it!",
    " was so awkward and goofy.",
    " never says anything good & never will.",
    " has made so many mistakes.",
    " bought and paid for by lobbyists!",
    " gave amnesty to criminal aliens guilty of sex offenses.",
    " is a choker, and once a choker, always a choker!",
    " looks like a little boy on stage.",
    " is a major lightweight with no credibility.",
    " is now a hostile basket case who feels jilted!",
    " has been no help, if anything, a major hindrance.",
    " made some of the dumbest political decisions of all time.",
    " comes off as a crazed & stumbling lunatic.",
    " started the illegal Rigged Witch Hunt.",
    " forgot to mention my phenomenal biz success rate.",
    " has never been able to make a comeback.",
    " didn’t have the mental capacity needed.",
    " was lazy as hell.",
    " is being so indignant.",
    " does little else but rant, rave & politic against me.",
    " should apologize for perpetrating this fraud against the American Public.",
    " was overrated.",
    " is wrong almost all of the time.",
    " is boring and totally biased.",
    " is wrong on so many subjects.",
    " has a major inferiority complex."




  ],

  "insult": [
    " Hokey garbage.",
    " Those who believe in tight border security, stopping illegal immigration & SMART trade deals w/other countries should boycott.",
    " Anyone who wants strong borders and good trade deals for the US should boycott.",
    " Total hypocrite.",
    " But nobody beats Trump!",
    " What the hell were you thinking when you married loser Russell Brand.",
    " If you were smart, which you are not, you would oppose the monstrous windfarms that will destroy your country.",
    " So many things are wrong!",
    " Fading out fast.",
    " A wiseguy with no talent.",
    " A total loser!",
    " We're not dealing with Albert Einstein.",
    " Average talent who is out of touch with reality.",


    " A waste!",
    " A total low-life!",
    " A real nut job!",
    " Another low I.Q. individual!",
    " Total Phony!",
    " Not good!",
    " Just another clueless politician!",
    " A pathetic figure!",
    " Low energy guy!",
    " No talent.",
    " Really sick!",
    " A stone cold LOSER.",
    " Another all talk, no action pol!",
    " A neurotic dope!",
    " USED!",
    " Wake up Punchy!",
    " FRAUD!",
    " An embarrassment to our Country and to Democracy!",
    " A total disaster!",
    " Very disloyal.",
    " No honor!",
    " ALL TALK AND NO ACTION!",
    " Psycho!",
    " Like @Rosie O'Donnell, a total loser!",
    " Not a fan.",
    " Major loser, zero credibility!",
    " YOU'RE FIRED.",
    " Will be wacky in the unemployment line.",
    " All talk, talk, talk - no action or results.",
    " Never a big fan!",
    " A total joke!",
    " A bad messenger for estab!",
    " An all talk, no action dummy!",
    " Poor work ethic!",
    " Not much power or insight!",
    " A third rate talent!",
    " Really dumb puppet.",
    " BORING."



  ],

  "kicker": [
    " WIN!",
    " Lets do an I.Q. test!",
    " What a stiff. What a stiff!",
    " SO SAD.",
    " Show courage!",
    " Who cares!",
    " MAKE AMERICA GREAT AGAIN!",
    " Make America Great Again.",
    " Funny!",
    " Get smart!",
    " The word is getting out, MAKE AMERICA GREAT AGAIN!",
    " Wow!",
    " #MakeAmericaGreatAgain",
    " I am fighting for our Veterans!",
    " Let's ‪#‎MakeAmericaGreatAgain‬!",
    " Remember, Univision apologized!",
    " Tiny children are not horses.",
    " THE UNITED STATES HAS ENOUGH PROBLEMS!",
    " Save our children and their future.",

    " Media rigging election!",
    " Too bad!",
    " We're going to win bigly.",
    " Sad!",
    " Really Sad!",
    " The Witch Hunt continues!",
    " Sad & irrelevant!",
    " A NEW LOW!",
    " But watch – I will win!",
    " DISGRACE!",
    " Big stuff!"
  ],
  "niceQuotes": [
    "What a beautiful person!",
    "That one should be our president!",
    "I know the best people. And that's one of them.",
    "Fantastic, yuge potential!"
]
}

const lengths = {
  'descriptor after': insults.descriptor_after.length,
  'descriptor before': insults.descriptor_before.length,
  'subject in middle': insults.subject_in_middle.length,
  'predicate': insults.predicate.length,
  'insult': insults.insult.length,
  'kicker': insults.kicker.length,
  'nice quotes': insults.niceQuotes.length
}

module.exports = insults